// <auto-generated />
namespace BookWyrm.Data.MigrationHistory.TransactionMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddRandomKeyColumnToChronJobTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRandomKeyColumnToChronJobTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201812031635038_AddRandomKeyColumnToChronJobTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
